# Generated by Django 3.0.5 on 2020-05-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0003_auto_20200505_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='auto',
            new_name='author',
        ),
    ]
